AWSTemplateFormatVersion: "2010-09-09"
Description: "ecr stack: creates ecr repo and stores uri in parameter store"

Parameters:
  project:
    Type: String
    Default: mane
    Description: project name (e.g., mane, myapp)

  environment:
    Type: String
    Default: dev
    Description: deployment environment (e.g., dev, prod)

  owner:
    Type: String
    Default: sachin
    Description: resource owner

  region:
    Type: String
    Default: ap-south-1
    AllowedValues:
      - ap-south-1
      - us-east-1
      - us-west-1
      - eu-west-1
    ConstraintDescription: select a valid aws region

Resources:

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${project}-${environment}-ecr-repo"
      ImageScanningConfiguration:
        scanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      Tags:
        - Key: Name
          Value: !Sub "${project}-${environment}-ecr-repo"
        - Key: project
          Value: !Ref project
        - Key: environment
          Value: !Ref environment
        - Key: owner
          Value: !Ref owner

  ECRRepositoryUriSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${project}/${environment}/ecr/repository-uri"
      Type: String
      Value: !GetAtt ECRRepository.RepositoryUri
      Description: !Sub "ecr repo uri for ${project} in ${environment}"

Outputs:
  ecrRepositoryName:
    Description: name of the created ecr repository
    Value: !Ref ECRRepository
    Export:
      Name: !Sub "${project}-${environment}-ecr-repo-name"

  ecrRepositoryUri:
    Description: uri of the created ecr repository
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub "${project}-${environment}-ecr-repo-uri"

  ecrRepositoryUriSSMParam:
    Description: ssm parameter name storing the ecr uri
    Value: !Ref ECRRepositoryUriSSM
    Export:
      Name: !Sub "${project}-${environment}-ecr-repo-uri-ssm"
